local opt = vim.opt
local g = vim.g

opt.cursorline = true
opt.number = true
opt.relativenumber = true
opt.termguicolors = true
opt.cmdheight= 0
opt.signcolumn = "yes"
g.loaded_netrw = 1
g.loaded_netrwPlugin = 1
g.mapleader = " "
opt.expandtab = true
opt.smartindent = true
opt.wrap = false
opt.showmatch = true
opt.backup = false
opt.errorbells = false
opt.swapfile = false
vim.o.shell = "zsh"
